Error being raised - I can't figure out why. Likely going to abandon since this seems like way more work than it should be...
Traceback (most recent call last):
  File "/Users/alexanderfournier/PycharmProjects/Olympics/util/ConvertXLSX.py", line 37, in <module>
    xl_workbook = xlrd.open_workbook(file)
  File "/Users/alexanderfournier/PycharmProjects/Olympics/venv/lib/python3.9/site-packages/xlrd/__init__.py", line 172, in open_workbook
    bk = open_workbook_xls(
  File "/Users/alexanderfournier/PycharmProjects/Olympics/venv/lib/python3.9/site-packages/xlrd/book.py", line 79, in open_workbook_xls
    biff_version = bk.getbof(XL_WORKBOOK_GLOBALS)
  File "/Users/alexanderfournier/PycharmProjects/Olympics/venv/lib/python3.9/site-packages/xlrd/book.py", line 1284, in getbof
    bof_error('Expected BOF record; found %r' % self.mem[savpos:savpos+8])
  File "/Users/alexanderfournier/PycharmProjects/Olympics/venv/lib/python3.9/site-packages/xlrd/book.py", line 1278, in bof_error
    raise XLRDError('Unsupported format, or corrupt file: ' + msg)
xlrd.biffh.XLRDError: Unsupported format, or corrupt file: Expected BOF record; found b'\x00\x00\x00\x01Bud1'